### ISSUE TITLE
java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0

### ISSUE THREAD

**Issue by RavinaBhayani** [mitchtabian/Google-Maps-Google-Places#1]
FATAL EXCEPTION: main
                                                                                           Process: com.example.ravina.googlemapsgoogleplaces, PID: 10740
                                                                                           java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0
                                                                                               at com.google.android.gms.common.internal.zzbq.zza(Unknown Source)
                                                                                               at com.google.android.gms.common.api.internal.zzi.zza(Unknown Source)
                                                                                               at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                                               at com.example.ravina.googlemapsgoogleplaces.MapActivity.init(MapActivity.java:100)
                                                                                               at com.example.ravina.googlemapsgoogleplaces.MapActivity.onMapReady(MapActivity.java:203)
                                                                                               at com.google.android.gms.maps.zzak.zza(Unknown Source)
                                                                                               at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source)
                                                                                               at android.os.Binder.transact(Binder.java:499)
                                                                                               at er.b(:com.google.android.gms.DynamiteModulesB@11951438:20)
                                                                                               at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB@11951438:5)
                                                                                               at com.google.maps.api.android.lib6.impl.bc.run(:com.google.android.gms.DynamiteModulesB@11951438:5)
                                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by mitchtabian** [comment]
I need more information. 

What did you try? 

What were the results?

What do you think the error is?

**Comment by codeForge13** [comment]
I found the solution.
weirdly, just cut and paste the line 

 mGoogleApiClient = new GoogleApiClient
                .Builder(this)
                .addApi(Places.GEO_DATA_API)
                .addApi(Places.PLACE_DETECTION_API)
                .enableAutoManage(this, 1,this)
                .build();

from init() to onCreate()

**Comment by jirawutch** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mynew.userapp, PID: 27612
    java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0
        at com.google.android.gms.common.internal.zzbq.zza(Unknown Source)
        at com.google.android.gms.common.api.internal.zzi.zza(Unknown Source)
        at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
        at com.mynew.userapp.RiderActivity.init(RiderActivity.java:597)
        at com.mynew.userapp.RiderActivity.onMapReady(RiderActivity.java:535)
        at com.google.android.gms.maps.zzak.zza(Unknown Source)
        at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source)
        at android.os.Binder.transact(Binder.java:387)
        at fv.b(:com.google.android.gms.dynamite_mapsdynamite@15088045@15.0.88 (040304-229857990):14)
        at com.google.android.gms.maps.internal.bd.a(:com.google.android.gms.dynamite_mapsdynamite@15088045@15.0.88 (040304-229857990):4)
        at com.google.maps.api.android.lib6.impl.bk.run(:com.google.android.gms.dynamite_mapsdynamite@15088045@15.0.88 (040304-229857990):4)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


---------------------------
same issue.
